### ISSUE TITLE
1.16.4 issue

### ISSUE THREAD

**Issue by MichaelDavidGK** [fr1kin/ForgeHax#329]
Not working on 1.16.4

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: dev/fiki/forgehax/api/event/Event
Exit Code: -1

[23:31:39 INFO ForgeHaxCoreTransformer::<init>@33]: ForgeHaxCore initializing
[23:31:43 INFO PatchScanner::<init>@49]: Skipping compile because service OptiFine is present
[23:31:43 INFO PatchScanner::<init>@49]: Skipping addQuad because service OptiFine is present
[23:31:47 ERROR PatchScanner::transform@132]: Could not find and transform method net/minecraft/client/renderer/entity/BoatRenderer :: render(Lnet/minecraft/entity/item/BoatEntity;FFLcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;I)V!

**Comment by fr1kin** [comment]
Why use 1.16.4 when 1.16.5 exists? #308

**Comment by MichaelDavidGK** [comment]
Some mods and servers I play on are not yet compatible with 1.16.5...
